name = "pixel-canvas-clash"
main = "worker.js"
compatibility_date = "2024-04-20" # Use a recent date

# Durable Object binding for game rooms
# This tells wrangler to make the GameRoom class available to the worker
# under the binding name "GAME_ROOM".
[[durable_objects.bindings]]
name = "GAME_ROOM"
class_name = "GameRoom"

# Migration for the Durable Object class
# This is required for wrangler to manage the DO class.
[[migrations]]
tag = "v1" # identifies this migration
new_classes = ["GameRoom"] # lists the new DO classes in this migration
